### ISSUE TITLE
BUG exception while executing task

### ISSUE THREAD

**Issue by Fargus-Van-Crystal-de-Mindark** [ItsNathanG/PictureLogin#5]
```
[12:20:44]: [WARN] [PictureLogin] Plugin PictureLogin v1.6 generated an exception while executing task 10104
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 8
at me.itsnathang.picturelogin.config.ConfigManager.getMessage(ConfigManager.java:56) ~[?:?]
at me.itsnathang.picturelogin.util.PictureUtil.createPictureMessage(PictureUtil.java:75) ~[?:?]
at me.itsnathang.picturelogin.util.PictureWrapper.getMessage(PictureWrapper.java:41) ~[?:?]
at me.itsnathang.picturelogin.util.PictureWrapper.sendImage(PictureWrapper.java:48) ~[?:?]
at me.itsnathang.picturelogin.util.PictureWrapper.run(PictureWrapper.java:22) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-253]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-253]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-253]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
Could u please add a delay in seconds configurable in the config file when the message is sent to the player please?

I using forcing installation of resource pack and players cannot view the picturelogin . please
